deploy:
  image: ruby:latest
  stage: deploy
  variables:
    HEROKU_APP_NAME: dbg-halloween2020
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY