image: debian:latest

production:
  type: deploy
  variables:
    HEROKU_APP_NAME: dbg-halloween2020
  only:
    - main
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
