port: 5000
url: http://localhost:5000

# paths to images by their ids
images: ['zPWQ1', 'iD1fC', 'lWCK2', 'PE0iw', 'ppqC0', 'N4q89', 'dRazV', 'qdIMZ']

# house numbers by their ids
houses: [3, 9, 13, 1, 3, 4, 8, 9, 10, 13, 1, 8, 3, 5, 6, 8, 10, 13, 15, 2]

db:
  host: localhost
  port: 3306
  user: root
  pass: ''
  name: ''

steam:
  key: ''
